//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARMEN_PORTAFOLIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonio
    {
        public string id { get; set; }
        public string UsuarioId { get; set; }
        public string IP { get; set; }
        public string Nombre { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
